#!/usr/bin/bash

unset LD_PRELOAD

info() {
  printf "\033[;32m%s\033[0m\n" "$@"
}

warn() {
  printf "\033[;33m%s\033[0m\n" "$@"
}

erro() {
  printf "\033[;31m%s\033[0m\n" "$@"
}

die() {
  erro "$@"
  exit 1
}

usage() {
  cat<<__EOF__
Usage: start-wine-desktop [OPTIONS]

OPTIONS:
    --64        Start with wine64, use prefix $HOME/.wine64
    --32        Start with wine, use prefix $HOME/.wine
    --help, -h  Show this help
__EOF__
}

export BOX64_LOG=0
export BOX64_NOBANNER=1
export BOX86_LOG=0
export BOX86_NOBANNER=1

if [[ $# -eq 0 ]]; then
  erro "Need an option"
  usage
  exit 1
fi

if [[ $# -ne 0 ]]; then
  case "$1" in
    "--64")
      export WINE=wine64
      export WINEPREFIX="$HOME/.wine64"
      export WINEARCH=win64
      ;;
    "--32")
      export WINE=wine
      export WINEPREFIX="$HOME/.wine"
      export WINEARCH=win32
      ;;
    "--help" | "-h" )
      usage
      exit 0
      ;;
    "*")
      erro "unknow option: $1"
      exit 1
      ;;
    esac
fi

wine_desktop_log() {
  echo "$@" > /dev/null
}

start_wine_desktop() {
  if ! [[ -d "$WINEPREFIX" ]]; then
    warn "Can not find prefix: '$WINEPREFIX', creating it..."
    ${WINE} wineboot &> /dev/null || die "Can not run 'wineboot'"
  fi
  cd "$WINEPREFIX" || die "Can not change work directory into prefix"
  wineserver -k &> /dev/null
  wineserver -p
  info "Wine desktop is starting in background."
  $EXEC "$WINE" explorer.exe /desktop=shell,"$RESOLUTION" &> wine_desktop_log &
}

# $WINE_DESKTOP_KEEP will keep wine64 in front end
if [[ -n "$WINE_DESKTOP_KEEP" ]] && [[ $WINE_DESKTOP_KEEP -eq 1 ]]; then
  start_wine_desktop
  warn "type 'q' or 'quit' to exit"
  while read -r -p "> " line; do
    case "$line" in
      "quit" | "q")
        wineserver -k
        info "wine desktop stopped"
        break
        ;;
      *)
        warn "type 'q' or 'quit' to exit"
        ;;
    esac
  done
else
  warn "If you want to stop it from console, use 'wineserver -k'"
  export EXEC="exec"
  start_wine_desktop
fi
