#!/usr/bin/bash

unset LD_PRELOAD

info() {
  printf "\033[;32m%s\033[0m\n" "$@"
}

warn() {
  printf "\033[;33m%s\033[0m\n" "$@"
}

erro() {
  printf "\033[;31m%s\033[0m\n" "$@"
}

die() {
  erro "$@"
  exit 1
}

stop_wine64() {
  export WINEARCH=win64
  wineserver -k &> /dev/null
}
stop_wine32() {
  export WINEARCH=win32
  wineserver -k &> /dev/null
}

start_wine_desktop() {
  if [[ -z "$WINEPREFIX" ]]; then
    die "WINEPREFIX is empty"
  fi
  if ! [[ -d "$WINEPREFIX" ]]; then
    warn "Can not find prefix: '$WINEPREFIX', creating it..."
    ${WINE} wineboot &> /dev/null || die "Can not run 'wineboot'"
  fi
  cd "$WINEPREFIX" || die "Can not change work directory into prefix"
  wineserver -k &> /dev/null
  wineserver -p
  info "Wine desktop is starting in background."
  $EXEC "$WINE" explorer.exe /desktop=shell,"$RESOLUTION" &> wine_desktop_log &
}

usage() {
  cat << __EOF__
Usage: start-wine-desktop [OPTIONS]

OPTIONS:
    --start64, --64   Start with wine64, use prefix $HOME/.wine64
    --start32, --32   Start with wine, use prefix $HOME/.wine
    --stop            Try to stop all wineserver
    --stop64          Stop wineserver that started by --start64
    --stop32          Stop wineserver that started by --start32
    --help, -h        Show this help
__EOF__
}

export BOX64_LOG=0
export BOX64_NOBANNER=1
export BOX86_LOG=0
export BOX86_NOBANNER=1

if [[ $# -eq 0 ]]; then
  erro "Need an option"
  usage
  exit 1
fi

case "$1" in
  --start64 | --64)
    export WINE="wine64"
    export WINEPREFIX="$HOME/.wine64"
    export WINEARCH="win64"
    ;;
  --start32 | --32)
    export WINE="wine"
    export WINEPREFIX="$HOME/.wine"
    export WINEARCH="win32"
    ;;
  --stop)
    stop_wine32
    stop_wine64
    ;;
  --stop64)
    stop_wine64
    ;;
  --stop32)
    stop_wine32
    ;;
  --help | -h)
    usage
    exit 0
    ;;
  *)
    erro "unknow option: $1"
    exit 1
    ;;
esac

# $WINE_DESKTOP_KEEP will keep wine64 in front end
if [[ -n "$WINE_DESKTOP_KEEP" ]] && [[ $WINE_DESKTOP_KEEP -eq 1 ]]; then
  start_wine_desktop
  warn "type 'q' or 'quit' to exit"
  while read -r -p "> " line; do
    case "$line" in
      quit | q)
        wineserver -k
        info "wine desktop stopped"
        break
        ;;
      *)
        warn "type 'q' or 'quit' to exit"
        ;;
    esac
  done
else
  warn "If you want to stop it from console, use 'wine-desktop --stop'"
  export EXEC="exec"
  start_wine_desktop
fi
